In [124]:
import pandas as pd
import numpy as np
import json
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,precision_score,f1_score,auc,confusion_matrix
import xgboost
pd.options.mode.chained_assignment = None

# Data Extraction and Merging

In [77]:
json_df_cols=[]
with open('..\samples\samples.json') as fh:
    data = fh.read()
data = data.split('\n')[0:-1]

list1=[]
list2=[]
list3=[]
list4=[]
list5=[]
list6=[]
list7=[]
list8=[]
list_id =[]

for rec in data:
    for k,v in json.loads(rec).items():
        if k == 'feature_1':
            list1.append(v)
        if k == 'feature_2':
            list2.append(v)
        if k == 'feature_3':
            list3.append(v)
        if k == 'feature_4':
            list4.append(v)
        if k == 'feature_5':
            list5.append(v)
        if k == 'feature_6':
            list6.append(v)
        if k == 'feature_7':
            list7.append(v)
        if k == 'feature_8':
            list8.append(v)  
        if k == 'user_id':
            list_id.append(v) 
json_df = pd.DataFrame(zip(list1,list2,list3,list4,list5,list6,list7,list8,list_id),
                       columns=['feature_1','feature_2','feature_3','feature_4','feature_5','feature_6',
                               'feature_7','feature_8','user_id'])

In [78]:
tsv_df = pd.read_csv('../samples/samples.tsv',sep='\t',header = None)
tsv_df.rename({0:'user_id',1:'Target'},inplace=True,axis=1)

In [79]:
with open('../samples/samples.custom') as fh:
    data = fh.read()
data = data.split('\n')[:-1]
list_9 = []
list_10 = []
list_uid = []
for rec in data:
    rec_list=rec.split('=')
    list_uid.append(rec_list[1].split('feature')[0])
    list_9.append(float(rec_list[2].split('feature')[0]))
    list_10.append(float(rec_list[3]))
    
custom_df = pd.DataFrame(zip(list_9,list_10,list_uid),columns=['feature_9','feature_10','user_id'])

In [80]:
final_df =custom_df.merge(json_df)
final_df = final_df.merge(tsv_df) 
final_df.head()

,feature_9,feature_10,user_id,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,Target
0,1.030976,2.943784,b5a1fa98242d4323a9b6a6bb2ca3747f,3.436425,C,-4.937046,33.473868,9042.470623,4,9.322450,0.041292,1
1,4.587145,2.485351,89edd08ff30b454fa104a40fae11a9dc,6.332699,B,3.764515,22.008889,0.063052,4,6.205812,0.003882,1
2,7.224021,3.397376,fc6d8a952bfd489da3048c4ca45168eb,7.967237,A,0.697326,28.058075,55.860686,1,5.007276,0.197398,0
3,8.285427,11.201489,bd2d492dd52e4c4dbc8a7939f8fefa95,4.774479,A,-2.106129,26.316815,0.001087,4,4.792960,0.000545,1
4,3.449477,7.423531,97fb36632f774a41a2f6b2544ef37a07,4.159423,B,-6.121677,18.003241,2134.946341,2,2.119493,60.838907,1

In [81]:
feature_cols = [col for col in final_df.columns if 'feature' in col]
X=final_df[feature_cols]
Y=final_df['Target']

# EDA

In [82]:
####Check for multicolinearity
X.corr()

,feature_9,feature_10,feature_1,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8
feature_9,1.000000,-0.000684,0.000496,0.004618,0.003556,0.001221,0.002435,-0.003440,0.001207
feature_10,-0.000684,1.000000,0.006105,-0.000050,-0.004722,-0.005333,0.003975,-0.002877,0.003133
feature_1,0.000496,0.006105,1.000000,0.008337,-0.006135,0.001831,0.002657,-0.004140,0.002016
feature_3,0.004618,-0.000050,0.008337,1.000000,-0.002417,0.003290,-0.003543,-0.000602,0.000041
feature_4,0.003556,-0.004722,-0.006135,-0.002417,1.000000,-0.001856,0.000722,0.003527,-0.002672
feature_5,0.001221,-0.005333,0.001831,0.003290,-0.001856,1.000000,-0.002398,0.001015,-0.000101
feature_6,0.002435,0.003975,0.002657,-0.003543,0.000722,-0.002398,1.000000,0.001305,-0.002738
feature_7,-0.003440,-0.002877,-0.004140,-0.000602,0.003527,0.001015,0.001305,1.000000,-0.001008
feature_8,0.001207,0.003133,0.002016,0.000041,-0.002672,-0.000101,-0.002738,-0.001008,1.000000

In [83]:
####Check for null values
for col in X.columns:
    print(f'Null in column {col} = {sum(X[col].isnull())}')

Null in column feature_9 = 0
Null in column feature_10 = 0
Null in column feature_1 = 0
Null in column feature_2 = 0
Null in column feature_3 = 0
Null in column feature_4 = 0
Null in column feature_5 = 0
Null in column feature_6 = 0
Null in column feature_7 = 0
Null in column feature_8 = 0

In [84]:
####Class is not imbalanced. So not applying chnaging class ratio
Y.value_counts()

1    60954
0    39046
Name: Target, dtype: int64

# Data Processing

In [125]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,shuffle = True,random_state=42)
le = LabelEncoder()
x_train['feature_2'] = le.fit_transform(x_train['feature_2'])
x_test['feature_2'] = le.transform(x_test['feature_2'])

sc = StandardScaler()
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.transform(x_test)

# Model Fitting

In [126]:
lr = LogisticRegression()
lr.fit(x_train_sc,y_train)
pred = lr.predict(x_test_sc)
pred_train = lr.predict(x_train_sc)
print('Train F1 Score:',f1_score(y_train,pred_train))
print('Test F1 Score:',f1_score(y_test,pred))

Train F1 Score: 0.8768834901942604
Test F1 Score: 0.875881256584101

In [127]:
cols = x_train.columns
feature_coeff = list(zip(cols,lr.coef_[0]))
feature_coeff.sort(key = lambda x:x[1])
feature_coeff

[('feature_3', -2.1197914004990928),
 ('feature_1', -0.5746290936869113),
 ('feature_964', -0.019685761036193086),
 ('feature_5', -0.007020906621003085),
 ('feature_8', -0.004447758254786825),
 ('feature_2', 0.00030215707698828966),
 ('feature_4', 0.011408290829375708),
 ('feature_9', 0.013997208408806786),
 ('feature_6', 0.015015810655330072),
 ('feature_10', 0.23018953509749715),
 ('feature_7', 2.03960304744492)]

In [128]:
rf = RandomForestClassifier(max_depth=7,n_estimators=50)
rf.fit(x_train_sc,y_train)
pred = rf.predict(x_test_sc)
pred_train = rf.predict(x_train_sc)
print('Train F1 Score:',f1_score(y_train,pred_train))
print('Test F1 Score:',f1_score(y_test,pred))

Train F1 Score: 0.8797807343116543
Test F1 Score: 0.8735552780508543

In [129]:
xg = xgboost.XGBClassifier(max_depth = 2,n_estimators = 100)
xg.fit(x_train_sc,y_train)
pred = xg.predict(x_test_sc)
pred_train = xg.predict(x_train_sc)
print('Train F1 Score:',f1_score(y_train,pred_train))
print('Test F1 Score:',f1_score(y_test,pred))

[23:06:37] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

C:\Users\471436\AppData\Roaming\Python\Python36\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

Train F1 Score: 0.8780419807868783
Test F1 Score: 0.8742686890574215

svc = SVC()
svc.fit(x_train_sc,y_train)
pred = svc.predict(x_test_sc)
pred_train = svc.predict(x_train_sc)
print('Train Accuracy:',accuracy_score(y_train,pred_train))
print('Test Accuracy:',accuracy_score(y_test,pred))

# Feature Selection and Re-Modelling

In [132]:
'''Feature re-engineering to club low importance columns. 
We have removed 30% of the features without impacting the F1_Score'''

feature_cols = [col for col in final_df.columns if 'feature' in col]
X=final_df[feature_cols]
Y=final_df['Target']

X['feature_964'] = X['feature_9']*X['feature_6']*X['feature_4']
X['feature_58'] = X['feature_5']*X['feature_8']
X.drop(['feature_9','feature_6','feature_4','feature_5','feature_8'],axis=1,inplace=True)

x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,shuffle = True,random_state=42)
le = LabelEncoder()
x_train['feature_2'] = le.fit_transform(x_train['feature_2'])
x_test['feature_2'] = le.transform(x_test['feature_2'])

sc = StandardScaler()
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.transform(x_test)

lr = LogisticRegression()
lr.fit(x_train_sc,y_train)
pred = lr.predict(x_test_sc)
pred_train = lr.predict(x_train_sc)
print('Train F1_Score:',f1_score(y_train,pred_train))
print('Test F1_Score:',f1_score(y_test,pred))

Train F1_Score: 0.8768761807624104
Test F1_Score: 0.875881256584101

In [131]:
'''Removing 2 columns which has very low coefficients. 
We have removed 20% of the features without impacting the F1_Score'''

feature_cols = [col for col in final_df.columns if 'feature' in col and col not in ['feature_9','feature_8']]
X=final_df[feature_cols]
Y=final_df['Target']

x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,shuffle = True,random_state=42)
le = LabelEncoder()
x_train['feature_2'] = le.fit_transform(x_train['feature_2'])
x_test['feature_2'] = le.transform(x_test['feature_2'])

sc = StandardScaler()
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.transform(x_test)

lr = LogisticRegression()
lr.fit(x_train_sc,y_train)
pred = lr.predict(x_test_sc)
pred_train = lr.predict(x_train_sc)
print('Train F1_Score:',f1_score(y_train,pred_train))
print('Test F1_Score:',f1_score(y_test,pred))

Train F1_Score: 0.8769790676649899
Test F1_Score: 0.8759183232497839

# Understanding the Data

In [92]:
confusion_matrix(pred,y_test)

array([[ 9191,  2061],
       [ 2533, 16215]], dtype=int64)

In [139]:
fp_index=y_test[pred==1]==0
fn_index=y_test[pred==0]==1

In [140]:
final_df.iloc[fp_index[fp_index==True].index]
#The False positives have a bigger value of feature_7 or smaller value of feature_3 or both
#which contributes to the record being predicted as 1.

,feature_9,feature_10,user_id,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,Target
16130,5.173124,-0.219618,a069f156207e4859b1babc83f1e45e18,4.847880,A,7.149197,29.485590,0.007653,3,9.393033,0.044606,0
51685,1.840612,-2.188374,0f1610019c7c42919af2586d4584fe7e,7.808300,C,-8.609366,20.143686,0.004045,3,2.386555,5476.186026,0
85198,7.781526,-4.273623,d8747841c49f41bb9a6fd30f6b22d8cb,5.840957,C,-0.393440,26.017595,0.002307,3,5.089064,16.214487,0
39691,8.498695,-3.288687,0b6f9c46397144a3ab048f32f56bc727,0.583268,C,-4.722916,22.317931,7536.352537,3,1.625540,1.456604,0
49959,0.262875,5.764762,2d549db2ce1f4898a4bdfe8dd2727ea9,1.883512,B,-3.145892,24.059328,0.000798,3,0.842502,94.010935,0
...,...,...,...,...,...,...,...,...,...,...,...,...
99595,6.286606,0.039458,317cf712257b4226ac2053ec6155f74b,8.546131,C,-7.599093,22.907167,0.001915,3,3.602820,72.290262,0
59734,2.599070,-0.098298,501edd93d2594d2d9fb3c947f766c8f6,0.214824,B,-2.762027,20.727769,0.003119,2,1.151643,202.038872,0
50480,3.000009,3.297310,06e2dc6cf383483a8845017066ea4da3,5.566870,B,-2.294886,25.944327,12.481101,2,6.019838,7.103000,0
46242,0.441547,-7.651497,ad25e37f0e5c4a3896e97c1742466f06,1.659361,A,1.537950,20.510077,0.000019,2,5.818037,12.613588,0
38911,2.256220,-11.935640,4b97d270590e49128890ef87bc81985d,5.038250,C,1.342337,20.587261,0.034449,1,5.751425,248.823078,0

In [136]:
final_df.iloc[fn_index[fn_index==True].index]
#The False negitives have a smaller value of feature_7 or higher value of feature_3 or both
#which contributes to the record being predicted as 1.

,feature_9,feature_10,user_id,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,Target
16638,0.143213,-9.884485,2827e7df7cda4d4b928994ecbd5e2d71,2.897787,B,-0.775376,26.867505,2.623636,3,1.762590,0.062224,1
29130,7.067625,-1.120704,85aaa3cd0bb14e7c93c880ff71257287,3.107786,B,0.559586,24.408775,0.237718,3,1.422599,7.099255,1
4727,8.969303,-12.071728,62a2976d72f640688127479f0ab42f34,7.357787,C,-3.245442,26.412061,0.309073,4,0.799418,0.227047,1
15663,2.359594,5.507835,ab60caa6da2648bab1f79499348b0c09,5.174832,A,-3.243322,30.564327,0.031903,2,0.698960,8.848515,1
91957,7.963821,1.345677,9aba1fec558e45c3b371279f659caecb,2.392870,B,1.551496,28.411138,16.695539,2,2.931533,4.045002,1
...,...,...,...,...,...,...,...,...,...,...,...,...
24048,3.556977,-5.223637,928542dbdefd406f9bb4272398fff658,4.386021,A,7.992569,28.719301,4.958970,3,6.920000,0.009650,1
38981,9.537037,-1.711886,f4ead6cc44a0459bab00217fd43d4edc,7.577016,B,-0.143428,22.140931,0.159412,2,1.892616,0.035656,1
89579,7.717209,-5.982322,6cd2438d43964466842d803ebc3556a9,0.257175,C,4.387157,25.816778,9.669629,2,3.973872,0.547729,1
73189,6.735513,1.266478,3b80dd15d4d64f4e9c288e1241762866,5.089234,A,3.380819,24.639699,25.493351,2,3.345168,0.004480,1
42074,8.339071,-3.443485,78109420897c468d8f6f1072247b588d,6.759716,C,-5.265963,16.579578,0.000911,4,0.480423,0.111124,1